### ISSUE TITLE
Add a bit more vertical whitespace

### ISSUE THREAD

**Issue by berndsi** [thesocialdev/pushtester#2]
This is a minor issue but I would probably add a bit more vertical whitespace:
* after the buttons and
* after each log entry displayed in the list and/or highlight (e.g. make bold) the timestamps, so it's easier to see when a new message starts.

We could simplify the text on the top. (We probably don't even need the subscribe to topic at this time. Consider hiding it and the text for it.)

I think it would be good to log the instance id/token right away when the app starts.

(BTW. I like that it's easy to select the token in the UI, although for now I still prefer to copy it from logcat since that is on my dev machine.)

**Comment by thesocialdev** [comment]
Done.

**Comment by berndsi** [comment]
Would you push these changes? I don't see them yet.

**Comment by thesocialdev** [comment]
Sorry about that, just pushed them

**Comment by berndsi** [comment]
Looks great. :) The screenshot in the readme is outdated now, though.
